server:
  port: 5000

app:
  telegram-bot:
    name: ConverterCalculatorCurrencyBot
    token:
    webhookPath:

  currency-api:
    allCurrencyPath: https://api.getgeoapi.com/v2/currency/list?api_key=APITOKEN
    convertPath: https://api.getgeoapi.com/v2/currency/convert?api_key=APITOKEN&from={from}&to={to}&amount={amount}&format=json